create database if not exists TEST;



USE TEST;

CREATE TABLE IF NOT exists MEMBER(
	ID VARCHAR(13) primary KEY,
    PW VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE
);

DESC MEMBER;
DROP TABLE IF EXISTS BOARD;

CREATE TABLE IF NOT EXISTS BOARD(
	NUM INT auto_increment,
    TITLE VARCHAR(50) NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    VIEW INT NOT NULL DEFAULT 0,
    ID VARCHAR(13) NOT NULL,
    PRIMARY KEY(NUM),
    FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);
DESC BOARD;